import {retained} from '../core/output.js';
const request=r=>new Promise((resolve,reject)=>{r.onsuccess=()=>resolve(r.result);r.onerror=()=>reject(r.error);});
const complete=t=>new Promise((resolve,reject)=>{t.oncomplete=resolve;t.onerror=t.onabort=()=>reject(t.error||Error('Storage transaction failed'));});
export class SessionStore {
  constructor(){this.db=null;this.memory=new Map();this.state='memory-only';}
  async open(){if(!globalThis.indexedDB)return;try{this.db=await new Promise((resolve,reject)=>{let done=false;const timer=setTimeout(()=>{done=true;reject(Error('Browser database open blocked'));},8000);const r=indexedDB.open('mobmesh-console',1);r.onupgradeneeded=()=>{const d=r.result;d.createObjectStore('sessions',{keyPath:'sessionId'});const records=d.createObjectStore('records',{keyPath:'eventId'});records.createIndex('sessionId','sessionId');d.createObjectStore('history',{keyPath:'sessionId'});};r.onsuccess=()=>{clearTimeout(timer);if(done)r.result.close();else resolve(r.result);};r.onerror=()=>{clearTimeout(timer);reject(r.error);};r.onblocked=()=>{clearTimeout(timer);done=true;reject(Error('Close another console tab to finish the database upgrade'));};});this.db.onversionchange=()=>{this.db.close();this.db=null;this.state='memory-only';};this.state='saved';}catch(e){this.error=e.message;this.state='memory-only';}}
  async list(key=null){if(!this.db)return [...this.memory.values()].map(v=>v.session).filter(s=>!key||s.targetKey===key).sort((a,b)=>b.updatedAt-a.updatedAt);const t=this.db.transaction('sessions');return (await request(t.objectStore('sessions').getAll())).filter(s=>!key||s.targetKey===key).sort((a,b)=>b.updatedAt-a.updatedAt);}
  async create(key,route){const session={schemaVersion:1,sessionId:crypto.randomUUID(),targetKey:key,route,createdAt:Date.now(),updatedAt:Date.now(),catalogRevision:'draft-01',safeDraft:null};this.memory.set(session.sessionId,{session,records:[],history:[]});if(this.db){const t=this.db.transaction(['sessions','history'],'readwrite'),done=complete(t);t.objectStore('sessions').put(session);t.objectStore('history').put({sessionId:session.sessionId,entries:[]});await done;}return session;}
  async load(id){if(!this.db)return structuredClone(this.memory.get(id));const t=this.db.transaction(['sessions','records','history']);const [session,records,history]=await Promise.all([request(t.objectStore('sessions').get(id)),request(t.objectStore('records').index('sessionId').getAll(id)),request(t.objectStore('history').get(id))]);if(!session)throw Error('Saved session is no longer available');const value={session,records:records.sort((a,b)=>a.timestamp-b.timestamp||a.writerId.localeCompare(b.writerId)||a.sequence-b.sequence),history:history?.entries||[]};this.memory.set(id,structuredClone(value));return value;}
  async commit(id,records,history,draft){const existing=this.memory.get(id);if(!existing)throw Error('Unknown session');const result=retained(records);const session={...existing.session,updatedAt:Date.now(),safeDraft:draft};const value={session,records:result.records,history:history.slice(-500)};this.memory.set(id,value);if(!this.db)return {truncated:result.truncated,state:'memory-only'};try{const t=this.db.transaction(['sessions','records','history'],'readwrite'),done=complete(t),rs=t.objectStore('records');const old=await request(rs.index('sessionId').getAll(id));const ids=new Set(result.records.map(r=>r.eventId));for(const r of old)if(!ids.has(r.eventId))rs.delete(r.eventId);for(const r of result.records)rs.put(r);t.objectStore('sessions').put(session);t.objectStore('history').put({sessionId:id,entries:value.history});await done;return {truncated:result.truncated,state:'saved'};}catch(e){this.error=e.message;this.state='error';this.db.close();this.db=null;return {truncated:result.truncated,state:'error'};}}
  async delete(id){this.memory.delete(id);if(!this.db)return;const t=this.db.transaction(['sessions','records','history'],'readwrite'),done=complete(t);const rs=t.objectStore('records'),rows=await request(rs.index('sessionId').getAll(id));for(const r of rows)rs.delete(r.eventId);t.objectStore('sessions').delete(id);t.objectStore('history').delete(id);await done;}
  async clearAll(){this.memory.clear();if(!this.db)return;const t=this.db.transaction(['sessions','records','history'],'readwrite'),done=complete(t);for(const name of ['sessions','records','history'])t.objectStore(name).clear();await done;}
}
export async function acquireSession(id){if(!navigator.locks)return {available:false,release:()=>{}};let release;const available=await new Promise(resolve=>{navigator.locks.request('mobmesh-console-session-'+id,{ifAvailable:true},async lock=>{if(!lock){resolve(false);return;}resolve(true);await new Promise(r=>release=r);}).catch(()=>resolve(false));});return {available,release:()=>release?.()};}
