// Generated by generate-board-config.py compose-mods. Do not edit.
#pragma once

#include <helpers/ModHooks.h>


// Interposed above the example's mesh class, never below: MyMesh overrides the virtuals
// worth intercepting, so a class inserted underneath is never reached.
template <class Base>
class ModMesh : public Base {
public:
  using Base::Base;   // inherits the base constructor; the examples pass six arguments

  // No mod declared a mesh hook, so this adds no behaviour and no vtable entries.
};
