// Generated by generate-board-config.py compose-mods. Do not edit.
#include <string.h>
#include <helpers/ModHooks.h>
#include <helpers/esp32/HotspotOtaIntegration.h>
#include <helpers/esp32/TrySetIntegration.h>
#include <helpers/sync_settings/SyncIntegration.h>

bool modHandleCliCommand(uint32_t sender_timestamp, char* command, char* reply,
                         const char* fw_version, const char* fw_build_date) {
  const ModCliContext context = {sender_timestamp, fw_version, fw_build_date};
  if (hotspotOtaHandleCli(context, command, reply)) return true;
  if (trySetHandleCli(context, command, reply)) return true;
  if (syncCli(context, command, reply)) return true;
  // Upstream's poweroff never wakes, so it is never reachable; a mod that can wake handles it above.
  if (memcmp(command, "poweroff", 8) == 0 || memcmp(command, "shutdown", 8) == 0) {
    strcpy(reply, "ERR: poweroff not available in this build");
    return true;
  }
  return false;
}
