// Generated by generate-board-config.py compose-mods. Do not edit.
#include <helpers/ModHooks.h>
#include <target.h>
#include <helpers/esp32/HotspotOtaIntegration.h>
#include <helpers/esp32/TrySetIntegration.h>
#include <helpers/sync_settings/SyncIntegration.h>

bool modRadioInit(const char* build_id) {

  return hotspotOtaRadioInit(build_id);
}

void modLoop() {
  hotspotOtaLoop();
  trySetLoop();
  syncLoop();
}

bool modResolveRegion(mesh::Packet* packet, RegionMap* base, ModRegionMatch* out) {
  return syncRoute(packet, base, out);
}

bool modAllowFlood(const mesh::Packet* packet, bool scope_known) {
  return syncAllowFlood(packet, scope_known);
}

int modExportRegions(RegionMap* base, char* out, size_t capacity,
                     uint8_t excluded_flags) {
  return syncExportRegions(base, out, capacity, excluded_flags);
}

size_t modOwnerInfoMarker(uint8_t out[4]) {
  return syncOwnerInfoMarker(out);
}

void modObserveRecv(const mesh::Packet* packet, bool accepted,
                    const uint8_t scope_key[16]) {
  syncRecv(packet, accepted, scope_key);
}

void modObserveTx(uint32_t packet_id, bool succeeded) {
  syncTx(packet_id, succeeded);
}

bool modWantsPowerSaving() {
  return false;
}

void modBeforeDeepSleep() {
}

bool     modBoardRadioInit()               { return radio_init(); }
void     modBoardReboot()                  { board.reboot(); }
uint16_t modBoardBattMilliVolts()          { return board.getBattMilliVolts(); }
void     modBoardDeepSleep(uint32_t secs)  { board.enterDeepSleep(secs); }
void     modBoardInhibitSleep(bool inhibit) { board.setInhibitSleep(inhibit); }
uint32_t modClockGet()                     { return rtc_clock.getCurrentTime(); }
void     modClockSet(uint32_t epoch)       { rtc_clock.setCurrentTime(epoch); }

#ifdef MOBMESH_HAS_FEM_LNA
bool modFemLnaAvailable()  { return board.loRaFEMControl.isLnaCanControl(); }
bool modFemLnaGet()        { return board.loRaFEMControl.isLNAEnabled(); }
void modFemLnaSet(bool on) {
  board.loRaFEMControl.setLNAEnable(on);
  board.loRaFEMControl.setRxModeEnable();
}
#else
bool modFemLnaAvailable()  { return false; }
bool modFemLnaGet()        { return false; }
void modFemLnaSet(bool on) { }
#endif
