// Generated by generate-board-config.py compose-mods. Do not edit.
#include <helpers/ModHooks.h>
#include <target.h>
#include <helpers/esp32/HotspotOtaIntegration.h>
#include <helpers/esp32/TrySetIntegration.h>

bool modRadioInit(const char* build_id) {

  return hotspotOtaRadioInit(build_id);
}

void modLoop() {
  hotspotOtaLoop();
  trySetLoop();
}

bool modResolveRegion(mesh::Packet* packet, RegionMap* base, ModRegionMatch* out) {
  return false;
}

bool modAllowFlood(const mesh::Packet* packet, bool scope_known) {
  return true;
}

int modExportRegions(RegionMap* base, char* out, size_t capacity,
                     uint8_t excluded_flags) {
  return -1;
}

void modAppendOwnerInfo(char* out, size_t capacity) {

}

void modObserveRecv(const mesh::Packet*, bool, const uint8_t*) {}

void modObserveTx(uint32_t, bool) {}

bool modWantsPowerSaving() {
  return false;
}

void modBeforeDeepSleep() {
}

bool     modBoardRadioInit()               { return radio_init(); }
void     modBoardReboot()                  { board.reboot(); }
uint16_t modBoardBattMilliVolts()          { return board.getBattMilliVolts(); }
void     modBoardDeepSleep(uint32_t secs)  { board.enterDeepSleep(secs); }
void     modBoardInhibitSleep(bool inhibit) { board.setInhibitSleep(inhibit); }
uint32_t modClockGet()                     { return rtc_clock.getCurrentTime(); }
void     modClockSet(uint32_t epoch)       { rtc_clock.setCurrentTime(epoch); }

#ifdef MOBMESH_HAS_FEM_LNA
bool modFemLnaAvailable()  { return board.loRaFEMControl.isLnaCanControl(); }
bool modFemLnaGet()        { return board.loRaFEMControl.isLNAEnabled(); }
void modFemLnaSet(bool on) {
  board.loRaFEMControl.setLNAEnable(on);
  board.loRaFEMControl.setRxModeEnable();
}
#else
bool modFemLnaAvailable()  { return false; }
bool modFemLnaGet()        { return false; }
void modFemLnaSet(bool on) { }
#endif
