"""Snapshot the composed sources every shipped target actually builds against.

The fixtures under fixtures/composition/ are checked in as reviewed expected output, not
regenerated by the test. Comparing the generator against its own output would verify
nothing; comparing it against a file a human approved is what catches an unintended
change to what gets compiled into shipped firmware.
"""

import argparse
import importlib.util
import json
import tempfile
import unittest
from pathlib import Path

TESTS_DIR = Path(__file__).resolve().parent
SCRIPT_PATH = TESTS_DIR.parent / "generate-board-config.py"
FIXTURES = TESTS_DIR / "fixtures" / "composition"
BUILD_PLAN_FIXTURE = TESTS_DIR / "fixtures" / "build_plan.json"

spec = importlib.util.spec_from_file_location("generate_board_config_fixtures", SCRIPT_PATH)
gbc = importlib.util.module_from_spec(spec)
spec.loader.exec_module(gbc)

OUTPUTS = {
    "ModHooks.cpp": "src/helpers/ModHooks.cpp",
    "CommonCliMods.cpp": "src/helpers/esp32/CommonCliMods.cpp",
}


def shipped_mod_sets():
    """The distinct mod lists across every target in build-targets.yaml."""
    plan = gbc.ProjectModel.load(gbc.REPO_ROOT).build_plan
    return {tuple(target["mods"]) for target in json.loads(plan.matrix_json())["include"]}


def fixture_dir(mods):
    return FIXTURES / "_".join(mods)


class CompositionFixtureTestCase(unittest.TestCase):
    def compose(self, mods):
        temp = tempfile.TemporaryDirectory()
        self.addCleanup(temp.cleanup)
        upstream = Path(temp.name)
        gbc.cmd_compose_mods(argparse.Namespace(upstream=str(upstream), mods=",".join(mods)))
        return upstream

    def test_every_shipped_composition_has_a_fixture(self):
        # A new target combination must not reach production without its expected output
        # being reviewed and checked in.
        for mods in sorted(shipped_mod_sets()):
            with self.subTest(mods=mods):
                self.assertTrue(fixture_dir(mods).is_dir(),
                                f"no checked-in fixture for composition {'_'.join(mods)}")

    def test_generated_sources_match_the_reviewed_fixtures(self):
        for mods in sorted(shipped_mod_sets()):
            upstream = self.compose(mods)
            for name, relative in OUTPUTS.items():
                with self.subTest(mods=mods, output=name):
                    expected = (fixture_dir(mods) / name).read_text()
                    self.assertEqual((upstream / relative).read_text(), expected)


class BuildPlanFixtureTestCase(unittest.TestCase):
    def test_build_plan_matches_the_reviewed_fixture(self):
        # Board facts, capabilities, asset names and release identity all resolve through this
        # plan, so a change here changes what ships. It should never pass unreviewed.
        plan = gbc.ProjectModel.load(gbc.REPO_ROOT).build_plan
        expected = json.loads(BUILD_PLAN_FIXTURE.read_text())
        self.assertEqual(plan.as_dict(), expected)


if __name__ == "__main__":
    unittest.main()
