#pragma once

#if !defined(SYNC_SETTINGS_WITH_REGION) && \
    !defined(SYNC_SETTINGS_WITHOUT_REGION)
#define SYNC_SETTINGS_WITH_REGION 1
#endif

#if !defined(SYNC_SETTINGS_WITH_POLICY) && \
    !defined(SYNC_SETTINGS_WITHOUT_POLICY)
#define SYNC_SETTINGS_WITH_POLICY 1
#endif

#if !defined(SYNC_SETTINGS_WITH_RADIO) && \
    !defined(SYNC_SETTINGS_WITHOUT_RADIO)
#define SYNC_SETTINGS_WITH_RADIO 1
#endif

#if !defined(SYNC_SETTINGS_WITH_TIME) && \
    !defined(SYNC_SETTINGS_WITHOUT_TIME)
#define SYNC_SETTINGS_WITH_TIME 1
#endif

#ifndef SYNC_SETTINGS_WITH_REGION
#define SYNC_SETTINGS_WITH_REGION 0
#endif

#ifndef SYNC_SETTINGS_WITH_POLICY
#define SYNC_SETTINGS_WITH_POLICY 0
#endif

#ifndef SYNC_SETTINGS_WITH_RADIO
#define SYNC_SETTINGS_WITH_RADIO 0
#endif

#ifndef SYNC_SETTINGS_WITH_TIME
#define SYNC_SETTINGS_WITH_TIME 0
#endif

#if !SYNC_SETTINGS_WITH_REGION && !SYNC_SETTINGS_WITH_POLICY && \
    !SYNC_SETTINGS_WITH_RADIO
#error "sync-settings requires at least one dataset"
#endif

#define SYNC_SETTINGS_DATASET_COUNT \
  (SYNC_SETTINGS_WITH_REGION + SYNC_SETTINGS_WITH_POLICY + SYNC_SETTINGS_WITH_RADIO)
