#!/usr/bin/env python3
"""
Single source of truth for per-board config, split two ways:

  - "flags"       prints the exact `-D KEY=VALUE` (and, if set,
                   `board_build.partitions = ...`) lines that should exist in
                   a board's variant platformio.ini, derived from
                   variants/<board>/overrides.yaml. Used both to help a human
                   author/update a mod's patch, and by CI to verify the lines
                   actually present in the patch haven't drifted from
                   overrides.yaml.

  - "boards-json"  merges upstream's boards/<board>.json (mcu, flash size,
                   USB hwids, psram -- read directly, never duplicated),
                   variants/<board>/overrides.yaml's `flasher:` facts, and
                   partition byte offsets parsed from an actual built
                   partitions.bin (never hand-entered), into
                   pages/flasher/boards.json. Only the given board/variant
                   entry is touched; everything else in the file is
                   preserved as-is.

  - "resolve-targets"  reads build-targets.yaml (the single source of truth
                   for what gets built) and each listed mod's mods/<name>/mod.yaml,
                   computes each target's asset_basename, and emits the full
                   CI build matrix as JSON.

  - "inject-env"  composes the env_flag/build_src_filter entries declared by
                   each of a target's mods (mods/<name>/patches/*.meta.yaml)
                   with the board's overrides.yaml build_flags/
                   partitions_override, and inserts the result directly into
                   the given [env:<name>] section of a platformio.ini. Fails
                   loudly rather than guessing if the section or an expected
                   key can't be found, or if two mods claim the same env_flag.

Requires PyYAML (pip install pyyaml).
"""
import argparse
import json
import re
import shutil
import struct
import sys
from pathlib import Path

try:
    import yaml
except ImportError:
    sys.exit("error: PyYAML is required (pip install pyyaml)")

REPO_ROOT = Path(__file__).resolve().parent.parent

# Bootloader isn't part of the partition table itself -- its flash offset is
# a fixed constant per chip family (ESP-IDF/Arduino convention), not encoded
# in partitions.bin.
BOOTLOADER_OFFSET_BY_MCU_PREFIX = {
    "esp32": "0x1000",     # original ESP32 only
    "esp32s2": "0x0",
    "esp32s3": "0x0",
    "esp32c3": "0x0",
    "esp32c6": "0x0",
    "esp32h2": "0x0",
}
# The partition table's own flash offset is always this fixed value by
# convention -- also not encoded inside partitions.bin.
PARTITION_TABLE_OFFSET = "0x8000"

GENERATED_NOTICE = (
    "Auto-generated by scripts/generate-board-config.py from "
    "variants/<board>/overrides.yaml and this build's partitions.bin. "
    "Do not edit this file manually -- changes will be overwritten on the next build."
)

PARTITION_ENTRY_SIZE = 32
PARTITION_MAGIC = b"\xAA\x50"
PARTITION_TYPE_APP = 0x00
PARTITION_TYPE_DATA = 0x01
APP_SUBTYPE_OTA_0 = 0x10
APP_SUBTYPE_OTA_1 = 0x11
DATA_SUBTYPE_OTA = 0x00  # "otadata"


def bootloader_offset_for_mcu(mcu: str) -> str:
    key = mcu.lower()
    if key not in BOOTLOADER_OFFSET_BY_MCU_PREFIX:
        raise ValueError(
            f"unknown mcu '{mcu}' -- add its bootloader flash offset to "
            f"BOOTLOADER_OFFSET_BY_MCU_PREFIX in {Path(__file__).name}"
        )
    return BOOTLOADER_OFFSET_BY_MCU_PREFIX[key]


def parse_partitions_bin(path: Path) -> dict:
    """Parse an ESP32 partition table binary, return offsets/sizes we need."""
    data = path.read_bytes()
    found = {}
    for i in range(0, len(data), PARTITION_ENTRY_SIZE):
        entry = data[i : i + PARTITION_ENTRY_SIZE]
        if len(entry) < PARTITION_ENTRY_SIZE or entry[0:2] != PARTITION_MAGIC:
            break  # end-of-table marker or padding
        ptype, subtype = entry[2], entry[3]
        offset, size = struct.unpack_from("<II", entry, 4)
        if ptype == PARTITION_TYPE_DATA and subtype == DATA_SUBTYPE_OTA:
            found["otadata"] = offset
        elif ptype == PARTITION_TYPE_APP and subtype == APP_SUBTYPE_OTA_0:
            found["app0"] = offset
            found["app0_size"] = size
        elif ptype == PARTITION_TYPE_APP and subtype == APP_SUBTYPE_OTA_1:
            found["app1"] = offset

    missing = {"otadata", "app0", "app1"} - found.keys()
    if missing:
        raise ValueError(
            f"partitions.bin at {path} is missing expected partition(s): {sorted(missing)} "
            "-- expected an otadata + ota_0 + ota_1 (dual-OTA) partition scheme"
        )
    return found


def load_overrides(board: str) -> dict:
    path = REPO_ROOT / "variants" / board / "overrides.yaml"
    if not path.exists():
        raise FileNotFoundError(f"no overrides file for board '{board}': {path}")
    with path.open() as f:
        return yaml.safe_load(f) or {}


def load_mod(mod_name: str) -> dict:
    path = REPO_ROOT / "mods" / mod_name / "mod.yaml"
    if not path.exists():
        raise FileNotFoundError(f"no mod.yaml for mod '{mod_name}': {path}")
    with path.open() as f:
        return yaml.safe_load(f) or {}


def load_build_targets() -> list:
    path = REPO_ROOT / "build-targets.yaml"
    if not path.exists():
        raise FileNotFoundError(f"build-targets.yaml not found: {path}")
    with path.open() as f:
        data = yaml.safe_load(f) or {}
    return data.get("targets") or []


def load_core_mods() -> list:
    path = REPO_ROOT / "build-targets.yaml"
    with path.open() as f:
        data = yaml.safe_load(f) or {}
    return data.get("core_mods") or []


def target_mods(target: dict, core: list = None) -> list:
    """core_mods first, then the target's own extras. Order is the apply order,
    so a target listing a core mod again does not move or duplicate it."""
    if core is None:
        core = load_core_mods()
    out = list(core)
    for m in target.get("mods") or []:
        if m not in out:
            out.append(m)
    return out


def load_mod_patch_sidecars(mod_name: str) -> list:
    patches_dir = REPO_ROOT / "mods" / mod_name / "patches"
    if not patches_dir.exists():
        raise FileNotFoundError(f"no patches dir for mod '{mod_name}': {patches_dir}")
    sidecars = sorted(patches_dir.glob("*.meta.yaml"))
    result = []
    for path in sidecars:
        with path.open() as f:
            result.append(yaml.safe_load(f) or {})
    return result


def load_upstream_board_json(upstream_dir: Path, board: str) -> dict:
    path = upstream_dir / "boards" / f"{board}.json"
    if path.exists():
        with path.open() as f:
            return json.load(f)

    # Not every board upstream builds actually ships a boards/<name>.json -- xiao_c3 has a
    # working variants/xiao_c3/ but no such file. Fall back to a copy of this chip's
    # PlatformIO board manifest vendored in this repo (see variants/<board>/board.json's
    # own _source_note for provenance) rather than failing outright.
    fallback_path = REPO_ROOT / "variants" / board / "board.json"
    if fallback_path.exists():
        with fallback_path.open() as f:
            return json.load(f)

    raise FileNotFoundError(
        f"upstream board definition not found: {path}, and no fallback at {fallback_path}"
    )


def cmd_flags(args):
    overrides = load_overrides(args.board)
    lines = []
    for key, value in (overrides.get("build_flags") or {}).items():
        if isinstance(value, str):
            lines.append(f'-D {key}=\'"{value}"\'')
        else:
            lines.append(f"-D {key}={value}")

    partitions_override = overrides.get("partitions_override")
    if partitions_override:
        lines.append(f"board_build.partitions = {partitions_override}")

    output = "\n".join(lines)
    if args.out:
        Path(args.out).write_text(output + "\n")
    else:
        print(output)


def cmd_boards_json(args):
    overrides = load_overrides(args.board)
    upstream = load_upstream_board_json(Path(args.upstream_dir), args.board)
    partitions = parse_partitions_bin(Path(args.partitions_bin))

    build = upstream.get("build", {})
    mcu = build.get("mcu")
    if not mcu:
        raise ValueError(f"upstream boards/{args.board}.json has no build.mcu field")

    board_entry = {
        "label": overrides["flasher"]["label"],
        "connectNote": overrides["flasher"]["connect_note"],
        "postFlashNote": overrides["flasher"]["post_flash_note"],
        # True when this board's partition table (variants/<board>/overrides.yaml's
        # partitions_override) differs from upstream's stock scheme -- e.g. a resized
        # spiffs partition. The web flasher uses this to know when it can't assume an
        # already-flashed device's on-flash partition table matches ours, and must
        # probe the running firmware first (see flasher.js) rather than offer an
        # in-place "Update" blind.
        "partitionsOverridden": bool(overrides.get("partitions_override")),
        "offsets": {
            "bootloader": bootloader_offset_for_mcu(mcu),
            "partitions": PARTITION_TABLE_OFFSET,
            "otadata": hex(partitions["otadata"]),
            "app0": hex(partitions["app0"]),
            "app1": hex(partitions["app1"]),
            "appMaxSize": hex(partitions["app0_size"]),
        },
    }

    output_path = Path(args.output)
    all_boards = json.loads(output_path.read_text()) if output_path.exists() else {}
    existing = all_boards.get(args.board, {})
    existing_variants = existing.get("variants", {})

    board_entry["variants"] = existing_variants
    variant_entry = {
        "label": args.variant_label,
        "assetBasename": args.asset_basename,
        "version": args.version,
        "firmwareFile": args.firmware_file,
    }

    # Optional per-variant CLI settings from overrides.yaml's
    # flasher.post_flash_commands. The flasher prepends these to the location
    # commands from member-config-*.json (see flasher.js), so a region can
    # override a board default. Omitted entirely when a variant has none, which
    # flasher.js reads as an empty list.
    post_flash = (overrides["flasher"].get("post_flash_commands") or {}).get(args.variant_id)
    if post_flash:
        variant_entry["postFlashCommands"] = list(post_flash)

    board_entry["variants"][args.variant_id] = variant_entry
    board_entry["bootApp0"] = existing.get("bootApp0", f"{args.board}/boot_app0.bin")
    board_entry["bootloaderFile"] = existing.get("bootloaderFile", f"{args.board}/bootloader.bin")
    board_entry["partitionsFile"] = existing.get("partitionsFile", f"{args.board}/partitions.bin")

    all_boards[args.board] = board_entry
    all_boards["_generated"] = GENERATED_NOTICE
    all_boards["_version"] = args.version
    output_path.write_text(json.dumps(all_boards, indent=2) + "\n")
    print(f"OK: updated '{args.board}' ({args.variant_id}) in {output_path}")


def cmd_resolve_targets(args):
    targets = load_build_targets()
    if not targets:
        sys.exit("error: build-targets.yaml has no targets")

    core = load_core_mods()
    rows = []
    for t in targets:
        for field in ("board", "role", "build_env", "upstream_tag_prefix", "release_title",
                      "asset_role_abbrev", "sync_docs", "vendor_flasher_assets", "make_latest"):
            if field not in t:
                sys.exit(f"error: build-targets.yaml entry for board '{t.get('board')}' "
                          f"role '{t.get('role')}' is missing required field '{field}'")

        mods = target_mods(t, core)
        if not mods:
            sys.exit(f"error: build-targets.yaml entry for board '{t.get('board')}' "
                      f"role '{t.get('role')}' resolves to no mods (set core_mods or mods)")

        # A mod may declare an empty suffix (e.g. a framework or failsafe rather
        # than a feature) to leave the asset filename unchanged.
        suffixes = [s for s in (load_mod(name)["suffix"] for name in mods) if s]
        asset_basename = "_".join([t["board"], t["asset_role_abbrev"], *suffixes])

        rows.append({
            "id": t["role"],
            "board_id": t["board"],
            "build_env": t["build_env"],
            "upstream_tag_prefix": t["upstream_tag_prefix"],
            "release_title": t["release_title"],
            "asset_basename": asset_basename,
            "sync_docs": t["sync_docs"],
            "vendor_flasher_assets": t["vendor_flasher_assets"],
            "make_latest": t["make_latest"],
            "mods": mods,
            # Optional. Raw flags appended after upstream's, so they can override
            # what the env already sets.
            "build_flags_append": t.get("build_flags_append") or [],
        })

    # Targets sharing an upstream_tag_prefix publish to the same shared release (see
    # build-release.yml's release_tag), so release_title/make_latest are release-level
    # facts, not per-target ones -- disagreement here would mean whichever job runs last
    # silently overwrites the release's name or latest-flag.
    by_prefix = {}
    for row in rows:
        by_prefix.setdefault(row["upstream_tag_prefix"], []).append(row)
    for prefix, group in by_prefix.items():
        for field in ("release_title", "make_latest"):
            values = {row[field] for row in group}
            if len(values) > 1:
                sys.exit(
                    f"error: build-targets.yaml targets sharing upstream_tag_prefix "
                    f"'{prefix}' disagree on '{field}': {values} -- they publish to the same "
                    f"release and must agree (boards: {[row['board_id'] for row in group]})"
                )

    # Exactly one target per board must vendor that board's flasher assets (bootloader/
    # partitions/boot_app0) -- zero means the web flasher's "New device" flow silently has
    # no data for that board (the original xiao_c3 gap); more than one is wasted duplicate
    # work writing the same board-keyed files from different roles.
    by_board = {}
    for row in rows:
        by_board.setdefault(row["board_id"], []).append(row)
    for board, group in by_board.items():
        vendors = [row for row in group if row["vendor_flasher_assets"]]
        if len(vendors) != 1:
            sys.exit(
                f"error: board '{board}' has {len(vendors)} targets with "
                f"vendor_flasher_assets: true (expected exactly 1): "
                f"{[row['id'] for row in vendors]}"
            )

    output = json.dumps({"include": rows})
    if args.out:
        Path(args.out).write_text(output + "\n")
    else:
        print(output)


def find_section(lines: list, env: str, ini_path: Path):
    header_re = re.compile(r"^\[env:" + re.escape(env) + r"\]\s*$")
    any_header_re = re.compile(r"^\[")
    start = None
    for i, line in enumerate(lines):
        if header_re.match(line.rstrip("\n")):
            start = i
            break
    if start is None:
        sys.exit(f"error: [env:{env}] section not found in {ini_path}")
    end = len(lines)
    for i in range(start + 1, len(lines)):
        if any_header_re.match(lines[i]):
            end = i
            break
    return start, end


def find_key_line(section_lines: list, key: str):
    pat = re.compile(r"^" + re.escape(key) + r"\s*=")
    for idx, line in enumerate(section_lines):
        if pat.match(line):
            return idx
    return None


def find_value_block_end(section_lines: list, key_idx: int):
    """Index of the last continuation line of a multi-line INI value.

    Continuations are indented; commented-out flags sit at column 0 between
    them, so skip those rather than treating them as the next key.
    """
    last = key_idx
    for i in range(key_idx + 1, len(section_lines)):
        line = section_lines[i]
        if not line.strip():
            break
        if line[:1].isspace():
            last = i
        elif not line.lstrip().startswith((";", "#")):
            break
    return last


def cmd_inject_env(args):
    board = args.board
    env = args.env
    ini_path = Path(args.platformio_ini)
    mods = args.mods.split(",")
    overrides = load_overrides(board)

    env_flag_owner = {}
    env_flag_lines = []
    src_filter_entries = []
    seen_src_filter = set()

    for mod_name in mods:
        for sidecar in load_mod_patch_sidecars(mod_name):
            flag = sidecar.get("env_flag")
            if flag:
                owner = env_flag_owner.get(flag)
                if owner is not None and owner != mod_name:
                    sys.exit(
                        f"error: env_flag '{flag}' is declared by both mod '{owner}' and "
                        f"mod '{mod_name}' -- two mods must not claim the same env_flag name"
                    )
                if owner is None:
                    env_flag_lines.append(f"-D {flag}=1")
                env_flag_owner[flag] = mod_name
            for entry in sidecar.get("build_src_filter") or []:
                if entry not in seen_src_filter:
                    src_filter_entries.append(entry)
                    seen_src_filter.add(entry)

    override_flag_lines = []
    for key, value in (overrides.get("build_flags") or {}).items():
        if isinstance(value, str):
            override_flag_lines.append(f'-D {key}=\'"{value}"\'')
        else:
            override_flag_lines.append(f"-D {key}={value}")

    # Raw flags appended after upstream's own, so they win when both set the same
    # macro (e.g. "-UDISPLAY_CLASS"). Prepended flags cannot. Board-level first,
    # then this target's.
    append_flag_lines = [str(f) for f in (overrides.get("build_flags_append") or [])]
    append_flag_lines += [f.strip() for f in (getattr(args, "append_flags", "") or "").split(",") if f.strip()]

    all_build_flags_lines = env_flag_lines + override_flag_lines
    partitions_override = overrides.get("partitions_override")

    lines = ini_path.read_text().splitlines(keepends=True)
    start, end = find_section(lines, env, ini_path)
    section_lines = lines[start:end]

    bf_idx = find_key_line(section_lines, "build_flags")
    if bf_idx is None:
        sys.exit(f"error: 'build_flags =' not found in [env:{env}] section of {ini_path}")

    if partitions_override:
        if any(l.strip().startswith("board_build.partitions") for l in section_lines):
            sys.exit(
                f"error: [env:{env}] in {ini_path} already has a board_build.partitions line "
                "-- refusing to insert a duplicate"
            )
        # The CSV lives in this repo (variants/<board>/), not in the freshly-cloned upstream
        # tree -- vendor it in before the build, since board_build.partitions is meaningless
        # if PlatformIO can't actually find the file at build time.
        src_csv = REPO_ROOT / "variants" / board / partitions_override
        if not src_csv.exists():
            sys.exit(f"error: partitions_override '{partitions_override}' for board '{board}' "
                      f"not found at {src_csv}")
        dest_csv = ini_path.parent / partitions_override
        shutil.copy(src_csv, dest_csv)
        # board_build.partitions resolves relative to the PlatformIO project root (where `pio
        # run` is invoked), not relative to this variant's own platformio.ini -- so the injected
        # value must include the variants/<board>/ prefix, not just the bare filename.
        project_relative_path = f"variants/{board}/{partitions_override}"
        section_lines[bf_idx:bf_idx] = [f"board_build.partitions = {project_relative_path}\n"]
        bf_idx += 1

    indent = "  "
    section_lines[bf_idx + 1 : bf_idx + 1] = [f"{indent}{l}\n" for l in all_build_flags_lines]

    if append_flag_lines:
        bf_end = find_value_block_end(section_lines, bf_idx)
        section_lines[bf_end + 1 : bf_end + 1] = [f"{indent}{l}\n" for l in append_flag_lines]

    if src_filter_entries:
        sf_idx = find_key_line(section_lines, "build_src_filter")
        if sf_idx is None:
            sys.exit(f"error: 'build_src_filter =' not found in [env:{env}] section of {ini_path}")
        section_lines[sf_idx + 1 : sf_idx + 1] = [f"{indent}{e}\n" for e in src_filter_entries]

    lines[start:end] = section_lines
    ini_path.write_text("".join(lines))
    print(
        f"OK: injected {len(all_build_flags_lines)} build flag(s)"
        + (f", {len(append_flag_lines)} appended flag(s)" if append_flag_lines else "")
        + (", 1 partitions override" if partitions_override else "")
        + (f", {len(src_filter_entries)} build_src_filter entrie(s)" if src_filter_entries else "")
        + f" into [env:{env}] in {ini_path}"
    )


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    sub = parser.add_subparsers(dest="command", required=True)

    p_flags = sub.add_parser("flags", help="print build-flag lines for a board's overrides")
    p_flags.add_argument("--board", required=True)
    p_flags.add_argument("--out", help="write to this file instead of stdout")
    p_flags.set_defaults(func=cmd_flags)

    p_bj = sub.add_parser("boards-json", help="regenerate a board/variant entry in pages/flasher/boards.json")
    p_bj.add_argument("--board", required=True)
    p_bj.add_argument("--upstream-dir", required=True)
    p_bj.add_argument("--partitions-bin", required=True)
    p_bj.add_argument("--variant-id", required=True)
    p_bj.add_argument("--variant-label", required=True)
    p_bj.add_argument("--asset-basename", required=True)
    p_bj.add_argument("--version", required=True)
    p_bj.add_argument("--firmware-file", required=True)
    p_bj.add_argument("--output", required=True)
    p_bj.set_defaults(func=cmd_boards_json)

    p_rt = sub.add_parser("resolve-targets", help="emit the CI build matrix from build-targets.yaml")
    p_rt.add_argument("--out", help="write JSON to this file instead of stdout")
    p_rt.set_defaults(func=cmd_resolve_targets)

    p_ie = sub.add_parser("inject-env", help="inject a target's mod + board flags into a platformio.ini env")
    p_ie.add_argument("--board", required=True)
    p_ie.add_argument("--env", required=True)
    p_ie.add_argument("--platformio-ini", required=True)
    p_ie.add_argument("--mods", required=True, help="comma-separated mod names, e.g. hotspot-ota")
    # Values start with '-', so argparse needs the --flag=value form:
    #   --append-flags="-UDISPLAY_CLASS,-UFOO"
    p_ie.add_argument(
        "--append-flags", default="",
        help="comma-separated raw flags appended after upstream's own, e.g. -UDISPLAY_CLASS. "
             "PlatformIO splits on spaces, so use the joined form (-UFOO, not -U FOO).",
    )
    p_ie.set_defaults(func=cmd_inject_env)

    args = parser.parse_args()
    args.func(args)


if __name__ == "__main__":
    main()
