#!/usr/bin/env python3
"""
Single source of truth for per-board config, split three ways:

  - "boards-json"  merges upstream's boards/<board>.json (mcu, flash size,
                   USB hwids, psram -- read directly, never duplicated),
                   variants/<board>/overrides.yaml's `flasher:` facts, and
                   partition byte offsets parsed from an actual built
                   partitions.bin (never hand-entered), into
                   pages/flasher/auto_boards.json. Only the given board/variant
                   entry is touched; everything else in the file is
                   preserved as-is.

  - "resolve-targets"  reads build-targets.yaml (the single source of truth
                   for what gets built) and each listed mod's mods/<name>/mod.yaml,
                   computes each target's asset_basename, and emits the full
                   CI build matrix as JSON.

  - "inject-env"  composes the env_flag/build_src_filter entries declared by
                   each of a target's mods (mods/<name>/patches/*.meta.yaml)
                   with the board's overrides.yaml build_values/
                   partitions_override, and inserts the result directly into
                   the given [env:<name>] section of a platformio.ini. Fails
                   loudly rather than guessing if the section or an expected
                   key can't be found, or if two mods claim the same env_flag.

  - "compose-mods" validates each selected mod's integration declaration and
                   generates the shim-owned hook and CLI aggregate sources.

Requires PyYAML (pip install pyyaml).
"""
import argparse
import json
import re
import shutil
import struct
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))

from mobmesh_tools.model import (
    Capability,
    CliIntegration,
    IntegrationPhase,
    PartitionLayout,
    ProjectModel,
)

REPO_ROOT = Path(__file__).resolve().parent.parent
SYMBOL_RE = re.compile(r"^[A-Za-z_][A-Za-z0-9_]*$")

# Bootloader isn't part of the partition table itself -- its flash offset is
# a fixed constant per chip family (ESP-IDF/Arduino convention), not encoded
# in partitions.bin.
BOOTLOADER_OFFSET_BY_MCU_PREFIX = {
    "esp32": "0x1000",     # original ESP32 only
    "esp32s2": "0x0",
    "esp32s3": "0x0",
    "esp32c3": "0x0",
    "esp32c6": "0x0",
    "esp32h2": "0x0",
}
# The partition table's own flash offset is always this fixed value by
# convention -- also not encoded inside partitions.bin.
PARTITION_TABLE_OFFSET = "0x8000"

GENERATED_NOTICE = (
    "Auto-generated by scripts/generate-board-config.py from "
    "variants/<board>/overrides.yaml and this build's partitions.bin. "
    "Do not edit this file manually -- changes will be overwritten on the next build."
)

PARTITION_ENTRY_SIZE = 32
PARTITION_MAGIC = b"\xAA\x50"
PARTITION_TYPE_APP = 0x00
PARTITION_TYPE_DATA = 0x01
APP_SUBTYPE_OTA_0 = 0x10
APP_SUBTYPE_OTA_1 = 0x11
DATA_SUBTYPE_OTA = 0x00  # "otadata"


def bootloader_offset_for_mcu(mcu: str) -> str:
    key = mcu.lower()
    if key not in BOOTLOADER_OFFSET_BY_MCU_PREFIX:
        raise ValueError(
            f"unknown mcu '{mcu}' -- add its bootloader flash offset to "
            f"BOOTLOADER_OFFSET_BY_MCU_PREFIX in {Path(__file__).name}"
        )
    return BOOTLOADER_OFFSET_BY_MCU_PREFIX[key]


def parse_partitions_bin(path: Path) -> PartitionLayout:
    """Parse an ESP32 partition table binary, return offsets/sizes we need."""
    data = path.read_bytes()
    found = {}
    for i in range(0, len(data), PARTITION_ENTRY_SIZE):
        entry = data[i : i + PARTITION_ENTRY_SIZE]
        if len(entry) < PARTITION_ENTRY_SIZE or entry[0:2] != PARTITION_MAGIC:
            break  # end-of-table marker or padding
        ptype, subtype = entry[2], entry[3]
        offset, size = struct.unpack_from("<II", entry, 4)
        if ptype == PARTITION_TYPE_DATA and subtype == DATA_SUBTYPE_OTA:
            found["otadata"] = offset
        elif ptype == PARTITION_TYPE_APP and subtype == APP_SUBTYPE_OTA_0:
            found["app0"] = offset
            found["app0_size"] = size
        elif ptype == PARTITION_TYPE_APP and subtype == APP_SUBTYPE_OTA_1:
            found["app1"] = offset

    missing = {"otadata", "app0", "app1"} - found.keys()
    if missing:
        raise ValueError(
            f"partitions.bin at {path} is missing expected partition(s): {sorted(missing)} "
            "-- expected an otadata + ota_0 + ota_1 (dual-OTA) partition scheme"
        )
    return PartitionLayout(
        otadata_offset=found["otadata"],
        app0_offset=found["app0"],
        app0_size=found["app0_size"],
        app1_offset=found["app1"],
    )


def load_board_profile(board: str):
    return ProjectModel.load_board(REPO_ROOT, board)


def load_mod_definition(mod_name: str):
    return ProjectModel.load_mod(REPO_ROOT, mod_name)


def selected_mods(value: str) -> list:
    mods = [name.strip() for name in value.split(",") if name.strip()]
    if len(mods) != len(set(mods)):
        raise ValueError(f"duplicate mod in selection: {mods}")
    return mods


def composition_outputs(mods: list) -> dict:
    owners = []
    for mod_name in mods:
        composition = load_mod_definition(mod_name).composition
        if composition:
            owners.append((mod_name, {"hooks": composition.hooks, "cli": composition.cli}))
    if len(owners) != 1:
        raise ValueError(
            f"selected mods must provide exactly one composition output owner, found {len(owners)}"
        )
    owner, outputs = owners[0]
    if set(outputs) != {"hooks", "cli"}:
        raise ValueError(f"mod '{owner}' composition outputs must be exactly hooks and cli")
    for name, value in outputs.items():
        path = Path(value)
        if path.is_absolute() or ".." in path.parts or path.suffix != ".cpp":
            raise ValueError(f"mod '{owner}' has invalid {name} composition output: {value}")
    if len(set(outputs.values())) != len(outputs):
        raise ValueError(f"mod '{owner}' composition outputs must be unique")
    return outputs


def load_integrations(mods: list) -> list:
    integrations = []
    symbols = {}
    radio_owner = None
    for order, mod_name in enumerate(mods):
        definition = load_mod_definition(mod_name)
        integration = definition.integration
        if not integration:
            continue

        header = integration.header
        header_path = Path(header)
        if header_path.is_absolute() or ".." in header_path.parts or header_path.suffix != ".h":
            raise ValueError(f"mod '{mod_name}' has invalid integration header: {header}")
        source_header = REPO_ROOT / "mods" / mod_name / "files" / "src" / header_path
        if not source_header.is_file():
            raise ValueError(f"mod '{mod_name}' integration header does not exist: {source_header}")
        header_text = source_header.read_text()

        hooks = integration.hooks
        parsed = {"mod": mod_name, "order": order, "header": header, "hooks": {}}
        for phase, declaration in hooks.items():
            phase_name = phase.value
            if phase is IntegrationPhase.CLI:
                if not isinstance(declaration, CliIntegration):
                    raise ValueError(f"mod '{mod_name}' has an invalid cli integration")
                symbol = declaration.handler
                priority = declaration.priority
                parsed["hooks"][phase_name] = {"symbol": symbol, "priority": priority}
            else:
                symbol = declaration
                parsed["hooks"][phase_name] = {"symbol": symbol}

            if not isinstance(symbol, str) or not SYMBOL_RE.fullmatch(symbol):
                raise ValueError(f"mod '{mod_name}' has invalid {phase_name} symbol: {symbol}")
            if not re.search(r"\b" + re.escape(symbol) + r"\s*\(", header_text):
                raise ValueError(
                    f"mod '{mod_name}' {phase_name} symbol '{symbol}' is not declared in {header}"
                )
            if symbol in symbols:
                raise ValueError(
                    f"integration symbol '{symbol}' is declared by both '{symbols[symbol]}' and '{mod_name}'"
                )
            symbols[symbol] = mod_name
            if phase is IntegrationPhase.RADIO_INIT_POLICY:
                if radio_owner is not None:
                    raise ValueError(
                        f"radio_init_policy is exclusive but claimed by '{radio_owner}' and '{mod_name}'"
                    )
                radio_owner = mod_name
        integrations.append(parsed)
    return integrations


def render_mod_hooks(integrations: list) -> str:
    includes = "\n".join(f"#include <{item['header']}>" for item in integrations)
    before = [item["hooks"]["before_radio_init"]["symbol"]
              for item in integrations if "before_radio_init" in item["hooks"]]
    radio = [item["hooks"]["radio_init_policy"]["symbol"]
             for item in integrations if "radio_init_policy" in item["hooks"]]
    loops = [item["hooks"]["loop"]["symbol"]
             for item in integrations if "loop" in item["hooks"]]
    wants = [item["hooks"]["wants_power_saving"]["symbol"]
             for item in integrations if "wants_power_saving" in item["hooks"]]

    before_calls = "\n".join(f"  {symbol}();" for symbol in before)
    loop_calls = "\n".join(f"  {symbol}();" for symbol in loops)
    radio_call = f"{radio[0]}(build_id)" if radio else "modBoardRadioInit()"
    wants_expr = " || ".join(f"{symbol}()" for symbol in wants) or "false"
    return f"""// Generated by generate-board-config.py compose-mods. Do not edit.
#include <helpers/ModHooks.h>
#include <target.h>
{includes}

bool modRadioInit(const char* build_id) {{
{before_calls}
  return {radio_call};
}}

void modLoop() {{
{loop_calls}
}}

bool modWantsPowerSaving() {{
  return {wants_expr};
}}

bool     modBoardRadioInit()               {{ return radio_init(); }}
void     modBoardReboot()                  {{ board.reboot(); }}
uint16_t modBoardBattMilliVolts()          {{ return board.getBattMilliVolts(); }}
void     modBoardDeepSleep(uint32_t secs)  {{ board.enterDeepSleep(secs); }}
void     modBoardInhibitSleep(bool inhibit) {{ board.setInhibitSleep(inhibit); }}
uint32_t modClockGet()                     {{ return rtc_clock.getCurrentTime(); }}
void     modClockSet(uint32_t epoch)       {{ rtc_clock.setCurrentTime(epoch); }}

#ifdef MOBMESH_HAS_FEM_LNA
bool modFemLnaAvailable()  {{ return board.loRaFEMControl.isLnaCanControl(); }}
bool modFemLnaGet()        {{ return board.loRaFEMControl.isLNAEnabled(); }}
void modFemLnaSet(bool on) {{
  board.loRaFEMControl.setLNAEnable(on);
  board.loRaFEMControl.setRxModeEnable();
}}
#else
bool modFemLnaAvailable()  {{ return false; }}
bool modFemLnaGet()        {{ return false; }}
void modFemLnaSet(bool on) {{ }}
#endif
"""


def render_mod_cli(integrations: list) -> str:
    includes = "\n".join(f"#include <{item['header']}>" for item in integrations)
    handlers = []
    for item in integrations:
        cli = item["hooks"].get("cli")
        if cli:
            handlers.append((cli["priority"], item["order"], cli["symbol"]))
    handlers.sort(key=lambda row: (-row[0], row[1]))
    calls = "\n".join(
        f"  if ({symbol}(context, command, reply)) return true;" for _, _, symbol in handlers
    )
    return f"""// Generated by generate-board-config.py compose-mods. Do not edit.
#include <helpers/ModHooks.h>
{includes}

bool modHandleCliCommand(uint32_t sender_timestamp, char* command, char* reply,
                         const char* fw_version, const char* fw_build_date) {{
  const ModCliContext context = {{sender_timestamp, fw_version, fw_build_date}};
{calls}
  return false;
}}
"""


def cmd_compose_mods(args):
    mods = selected_mods(args.mods)
    outputs = composition_outputs(mods)
    integrations = load_integrations(mods)
    upstream = Path(args.upstream)
    rendered = {
        "hooks": render_mod_hooks(integrations),
        "cli": render_mod_cli(integrations),
    }
    for name in ("hooks", "cli"):
        destination = upstream / outputs[name]
        if destination.exists():
            raise FileExistsError(
                f"composition would overwrite existing {destination.relative_to(upstream)}"
            )
        destination.parent.mkdir(parents=True, exist_ok=True)
        destination.write_text(rendered[name])
        print(f"OK: generated {destination.relative_to(upstream)}")


def load_mod_patch_sidecars(mod_name: str) -> list:
    return [
        {
            "env_flag": patch.env_flag,
            "build_src_filter": list(patch.build_src_filter),
        }
        for patch in load_mod_definition(mod_name).patches
    ]


def load_upstream_board_json(upstream_dir: Path, board: str) -> dict:
    path = upstream_dir / "boards" / f"{board}.json"
    if path.exists():
        with path.open() as f:
            return json.load(f)

    # Not every board upstream builds actually ships a boards/<name>.json -- xiao_c3 has a
    # working variants/xiao_c3/ but no such file. Fall back to a copy of this chip's
    # PlatformIO board manifest vendored in this repo (see variants/<board>/board.json's
    # own _source_note for provenance) rather than failing outright.
    fallback_path = REPO_ROOT / "variants" / board / "board.json"
    if fallback_path.exists():
        with fallback_path.open() as f:
            return json.load(f)

    raise FileNotFoundError(
        f"upstream board definition not found: {path}, and no fallback at {fallback_path}"
    )


def cmd_boards_json(args):
    board = load_board_profile(args.board)
    upstream = load_upstream_board_json(Path(args.upstream_dir), args.board)
    partitions = parse_partitions_bin(Path(args.partitions_bin))

    build = upstream.get("build", {})
    mcu = build.get("mcu")
    if not mcu:
        raise ValueError(f"upstream boards/{args.board}.json has no build.mcu field")

    board_entry = {
        "label": board.flasher.label,
        "connectNote": board.flasher.connect_note,
        "postFlashNote": board.flasher.post_flash_note,
        # True when this board's partition table (variants/<board>/overrides.yaml's
        # partitions_override) differs from upstream's stock scheme -- e.g. a resized
        # spiffs partition. The web flasher uses this to know when it can't assume an
        # already-flashed device's on-flash partition table matches this one, and must
        # probe the running firmware first (see flasher.js) rather than offer an
        # in-place "Update" blind.
        "partitionsOverridden": bool(board.partitions_override),
        # How to boot this board under emulation: the machine and binary, and the board
        # wiring the device models take as run-time properties. Absent, or enabled: false,
        # means the QEMU boot check skips this board rather than failing it -- for a board
        # whose hardware there is no model for.
        "qemu": {
            "enabled": board.qemu.enabled,
            "machine": board.qemu.machine,
            "binary": board.qemu.binary,
            "mcu": board.qemu.mcu,
            "mem": board.qemu.mem,
            "globals": dict(board.qemu.globals),
        },
        "offsets": {
            "bootloader": bootloader_offset_for_mcu(mcu),
            "partitions": PARTITION_TABLE_OFFSET,
            "otadata": hex(partitions.otadata_offset),
            "app0": hex(partitions.app0_offset),
            "app1": hex(partitions.app1_offset),
            "appMaxSize": hex(partitions.app0_size),
        },
    }

    output_path = Path(args.output)
    all_boards = json.loads(output_path.read_text()) if output_path.exists() else {}
    existing = all_boards.get(args.board, {})
    existing_variants = existing.get("variants", {})

    board_entry["variants"] = existing_variants
    variant_entry = {
        "label": args.variant_label,
        "assetBasename": args.asset_basename,
        "version": args.version,
        "firmwareFile": args.firmware_file,
    }

    # Optional per-variant CLI settings from overrides.yaml's
    # flasher.post_flash_commands. The flasher prepends these to the location
    # commands from member-config-*.json (see flasher.js), so a region can
    # override a board default. Omitted entirely when a variant has none, which
    # flasher.js reads as an empty list.
    post_flash = board.flasher.post_flash_commands.get(args.variant_id)
    if post_flash:
        variant_entry["postFlashCommands"] = list(post_flash)

    board_entry["variants"][args.variant_id] = variant_entry
    board_entry["bootApp0"] = existing.get("bootApp0", f"{args.board}/boot_app0.bin")
    board_entry["bootloaderFile"] = existing.get("bootloaderFile", f"{args.board}/bootloader.bin")
    board_entry["partitionsFile"] = existing.get("partitionsFile", f"{args.board}/partitions.bin")

    all_boards[args.board] = board_entry
    all_boards["_generated"] = GENERATED_NOTICE
    all_boards["_version"] = args.version
    output_path.write_text(json.dumps(all_boards, indent=2) + "\n")
    print(f"OK: updated '{args.board}' ({args.variant_id}) in {output_path}")


def cmd_resolve_targets(args):
    plan = ProjectModel.load(REPO_ROOT).build_plan
    output = plan.matrix_json()
    if args.plan_out:
        Path(args.plan_out).write_text(json.dumps(plan.as_dict(), indent=2) + "\n")
    if args.out:
        Path(args.out).write_text(output + "\n")
    else:
        print(output)


def cmd_project_info(args):
    model = ProjectModel.load(REPO_ROOT)
    if args.field == "ordered-mods":
        values = model.ordered_mods()
    elif args.field == "patches":
        values = tuple(
            str(patch.patch_path.relative_to(REPO_ROOT / "mods"))
            for name in model.ordered_mods()
            for patch in model.mods[name].patches
        )
    else:
        values = model.upstream_pr_entries()
    print(args.separator.join(values))


def cmd_validate_mods(args):
    model = ProjectModel.load(REPO_ROOT)
    mods = selected_mods(args.mods)
    model.validate_mod_selection(mods)
    print("OK: mod selection and patch dependency order are valid")


def find_section(lines: list, env: str, ini_path: Path):
    header_re = re.compile(r"^\[env:" + re.escape(env) + r"\]\s*$")
    any_header_re = re.compile(r"^\[")
    start = None
    for i, line in enumerate(lines):
        if header_re.match(line.rstrip("\n")):
            start = i
            break
    if start is None:
        sys.exit(f"error: [env:{env}] section not found in {ini_path}")
    end = len(lines)
    for i in range(start + 1, len(lines)):
        if any_header_re.match(lines[i]):
            end = i
            break
    return start, end


def find_key_line(section_lines: list, key: str):
    pat = re.compile(r"^" + re.escape(key) + r"\s*=")
    for idx, line in enumerate(section_lines):
        if pat.match(line):
            return idx
    return None


def find_value_block_end(section_lines: list, key_idx: int):
    """Index of the last continuation line of a multi-line INI value.

    Continuations are indented; commented-out flags sit at column 0 between
    them, so skip those rather than treating them as the next key.
    """
    last = key_idx
    for i in range(key_idx + 1, len(section_lines)):
        line = section_lines[i]
        if not line.strip():
            break
        if line[:1].isspace():
            last = i
        elif not line.lstrip().startswith((";", "#")):
            break
    return last


def cmd_copy_src(args):
    """Copy each mod's own source into the upstream clone, before any patch applies.

    mods/<name>/files/ mirrors the upstream root, so a mod can ship into variants/ as
    well as src/. A file no one else owns needs no diff to arrive; patches stay for what
    edits somebody else's file.
    """
    upstream = Path(args.upstream)
    copied = 0
    for mod in selected_mods(args.mods):
        load_mod_definition(mod)
        src = REPO_ROOT / "mods" / mod / "files"
        if not src.is_dir():
            continue
        for path in sorted(src.rglob("*")):
            if not path.is_file():
                continue
            dest = upstream / path.relative_to(src)
            if dest.exists():
                sys.exit(f"ERROR: {mod} would overwrite an existing {dest.relative_to(upstream)} "
                         f"-- upstream may have added a file of the same name")
            dest.parent.mkdir(parents=True, exist_ok=True)
            shutil.copy2(path, dest)
            copied += 1
    print(f"OK: copied {copied} mod source file(s) into {upstream}")


def cmd_inject_env(args):
    board = args.board
    env = args.env
    ini_path = Path(args.platformio_ini)
    mods = selected_mods(args.mods)
    board_profile = load_board_profile(board)

    env_flag_owner = {}
    env_flag_lines = []
    src_filter_entries = []
    seen_src_filter = set()

    for mod_name in mods:
        # A mod that ships its own source declares its flags once, in mod.yaml, and its
        # build_src_filter is derived from what is actually under files/ rather than
        # restated by hand. Sidecars still carry both for mods that are patch-only.
        definition = load_mod_definition(mod_name)
        mod_src = REPO_ROOT / "mods" / mod_name / "files" / "src"
        declared = [{"env_flag": f} for f in definition.env_flags]
        derived = [{"build_src_filter": [
            f"+<{path.relative_to(mod_src).as_posix()}>"
            for path in sorted(mod_src.rglob("*.cpp"))
        ]}] if mod_src.is_dir() else []
        generated = []
        composition = definition.composition
        outputs = (composition.hooks, composition.cli) if composition else ()
        for output in outputs:
            path = Path(output)
            if path.parts[:1] == ("src",) and path.suffix == ".cpp":
                generated.append(f"+<{Path(*path.parts[1:]).as_posix()}>")
        generated_sources = [{"build_src_filter": generated}] if generated else []
        for sidecar in declared + derived + generated_sources + load_mod_patch_sidecars(mod_name):
            flag = sidecar.get("env_flag")
            if flag:
                owner = env_flag_owner.get(flag)
                if owner is not None and owner != mod_name:
                    sys.exit(
                        f"error: env_flag '{flag}' is declared by both mod '{owner}' and "
                        f"mod '{mod_name}' -- two mods must not claim the same env_flag name"
                    )
                if owner is None:
                    env_flag_lines.append(f"-D {flag}=1")
                env_flag_owner[flag] = mod_name
            for entry in sidecar.get("build_src_filter") or []:
                if entry not in seen_src_filter:
                    src_filter_entries.append(entry)
                    seen_src_filter.add(entry)

    override_flag_lines = []
    build_values = dict(board_profile.build_values)
    if board_profile.capability(Capability.FEM_LNA_CONTROL).satisfies_requirement:
        build_values["MOBMESH_HAS_FEM_LNA"] = 1
    for key, value in build_values.items():
        if isinstance(value, str):
            override_flag_lines.append(f'-D {key}=\'"{value}"\'')
        else:
            override_flag_lines.append(f"-D {key}={value}")

    # Raw flags appended after upstream's own, so they win when both set the same
    # macro (e.g. "-UDISPLAY_CLASS"). Prepended flags cannot. Board-level first,
    # then this target's.
    append_flag_lines = list(board_profile.build_flags_append)
    append_flag_lines += [f.strip() for f in (getattr(args, "append_flags", "") or "").split(",") if f.strip()]

    all_build_flags_lines = env_flag_lines + override_flag_lines
    partitions_override = board_profile.partitions_override

    lines = ini_path.read_text().splitlines(keepends=True)
    start, end = find_section(lines, env, ini_path)
    section_lines = lines[start:end]

    bf_idx = find_key_line(section_lines, "build_flags")
    if bf_idx is None:
        sys.exit(f"error: 'build_flags =' not found in [env:{env}] section of {ini_path}")

    if partitions_override:
        if any(l.strip().startswith("board_build.partitions") for l in section_lines):
            sys.exit(
                f"error: [env:{env}] in {ini_path} already has a board_build.partitions line "
                "-- refusing to insert a duplicate"
            )
        # The CSV lives in this repo (variants/<board>/), not in the freshly-cloned upstream
        # tree -- vendor it in before the build, since board_build.partitions is meaningless
        # if PlatformIO can't actually find the file at build time.
        src_csv = REPO_ROOT / "variants" / board / partitions_override
        if not src_csv.exists():
            sys.exit(f"error: partitions_override '{partitions_override}' for board '{board}' "
                      f"not found at {src_csv}")
        dest_csv = ini_path.parent / partitions_override
        shutil.copy(src_csv, dest_csv)
        # board_build.partitions resolves relative to the PlatformIO project root (where `pio
        # run` is invoked), not relative to this variant's own platformio.ini -- so the injected
        # value must include the variants/<board>/ prefix, not just the bare filename.
        project_relative_path = f"variants/{board}/{partitions_override}"
        section_lines[bf_idx:bf_idx] = [f"board_build.partitions = {project_relative_path}\n"]
        bf_idx += 1

    indent = "  "
    section_lines[bf_idx + 1 : bf_idx + 1] = [f"{indent}{l}\n" for l in all_build_flags_lines]

    if append_flag_lines:
        bf_end = find_value_block_end(section_lines, bf_idx)
        section_lines[bf_end + 1 : bf_end + 1] = [f"{indent}{l}\n" for l in append_flag_lines]

    if src_filter_entries:
        sf_idx = find_key_line(section_lines, "build_src_filter")
        if sf_idx is None:
            sys.exit(f"error: 'build_src_filter =' not found in [env:{env}] section of {ini_path}")
        section_lines[sf_idx + 1 : sf_idx + 1] = [f"{indent}{e}\n" for e in src_filter_entries]

    lines[start:end] = section_lines
    ini_path.write_text("".join(lines))
    print(
        f"OK: injected {len(all_build_flags_lines)} build flag(s)"
        + (f", {len(append_flag_lines)} appended flag(s)" if append_flag_lines else "")
        + (", 1 partitions override" if partitions_override else "")
        + (f", {len(src_filter_entries)} build_src_filter entrie(s)" if src_filter_entries else "")
        + f" into [env:{env}] in {ini_path}"
    )


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    sub = parser.add_subparsers(dest="command", required=True)

    p_bj = sub.add_parser("boards-json", help="regenerate a board/variant entry in pages/flasher/auto_boards.json")
    p_bj.add_argument("--board", required=True)
    p_bj.add_argument("--upstream-dir", required=True)
    p_bj.add_argument("--partitions-bin", required=True)
    p_bj.add_argument("--variant-id", required=True)
    p_bj.add_argument("--variant-label", required=True)
    p_bj.add_argument("--asset-basename", required=True)
    p_bj.add_argument("--version", required=True)
    p_bj.add_argument("--firmware-file", required=True)
    p_bj.add_argument("--output", required=True)
    p_bj.set_defaults(func=cmd_boards_json)

    p_rt = sub.add_parser("resolve-targets", help="emit the CI build matrix from build-targets.yaml")
    p_rt.add_argument("--out", help="write JSON to this file instead of stdout")
    p_rt.add_argument("--plan-out", help="write the full resolved BuildPlan JSON to this file")
    p_rt.set_defaults(func=cmd_resolve_targets)

    p_pi = sub.add_parser("project-info", help="emit a typed project-model query")
    p_pi.add_argument("--field", choices=("ordered-mods", "patches", "upstream-prs"), required=True)
    p_pi.add_argument("--separator", default=" ")
    p_pi.set_defaults(func=cmd_project_info)

    p_vm = sub.add_parser("validate-mods", help="validate a selected mod and patch order")
    p_vm.add_argument("--mods", required=True, help="comma-separated mod names in application order")
    p_vm.set_defaults(func=cmd_validate_mods)

    p_ie = sub.add_parser("inject-env", help="inject a target's mod + board flags into a platformio.ini env")
    p_ie.add_argument("--board", required=True)
    p_ie.add_argument("--env", required=True)
    p_ie.add_argument("--platformio-ini", required=True)
    p_ie.add_argument("--mods", required=True, help="comma-separated mod names, e.g. hotspot-ota")
    # Values start with '-', so argparse needs the --flag=value form:
    #   --append-flags="-UDISPLAY_CLASS,-UFOO"
    p_ie.add_argument(
        "--append-flags", default="",
        help="comma-separated raw flags appended after upstream's own, e.g. -UDISPLAY_CLASS. "
             "PlatformIO splits on spaces, so use the joined form (-UFOO, not -U FOO).",
    )
    p_ie.set_defaults(func=cmd_inject_env)

    p_cs = sub.add_parser("copy-src", help="copy each mod's own source into the upstream clone")
    p_cs.add_argument("--upstream", required=True, help="path to the upstream clone's root")
    p_cs.add_argument("--mods", required=True, help="comma-separated mod names")
    p_cs.set_defaults(func=cmd_copy_src)

    p_cm = sub.add_parser("compose-mods", help="generate shim aggregate sources for selected mods")
    p_cm.add_argument("--upstream", required=True, help="path to the upstream clone's root")
    p_cm.add_argument("--mods", required=True, help="comma-separated mod names in composition order")
    p_cm.set_defaults(func=cmd_compose_mods)

    args = parser.parse_args()
    args.func(args)


if __name__ == "__main__":
    main()
