// Generated by generate-board-config.py compose-mods. Do not edit.
#include <helpers/ModHooks.h>
#include <helpers/esp32/HotspotOtaIntegration.h>

bool modHandleCliCommand(uint32_t sender_timestamp, char* command, char* reply,
                         const char* fw_version, const char* fw_build_date) {
  const ModCliContext context = {sender_timestamp, fw_version, fw_build_date};
  if (hotspotOtaHandleCli(context, command, reply)) return true;
  return false;
}
